name: Godot CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
         operating-system: [ubuntu-18.04, ubuntu-20.04]
         include:
           - operating-system: ubuntu-18.04
             path: Godot/Godot_v3.3.2-stable_linux_server.64
           - operating-system: ubuntu-20.04
             path: Godot/Godot_v3.3.2-stable_linux_server.64
    env: 
      GODOT_PATH: ${{ matrix.path }}
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: |
            sudo apt install unzip wget
            cd .. && mkdir Godot && cd Godot
            wget https://downloads.tuxfamily.org/godotengine/3.3.2/Godot_v3.3.2-stable_linux_server.64.zip
            unzip Godot_v3.3.2-stable_linux_server.64.zip
            cd ..
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Run
        run: | 
            cd ..
            python3 -m unittest Simulation-Factory-Godot.tests.connection_test

